var hierarchy =
[
    [ "BasicInfo", "structBasicInfo.html", null ],
    [ "BasicScene", "classBasicScene.html", null ],
    [ "BoundingBox", "structBoundingBox.html", null ],
    [ "ogl::Buffer", "classogl_1_1Buffer.html", [
      [ "ogl::ElementBuffer", "classogl_1_1ElementBuffer.html", null ],
      [ "ogl::FrameBuffer", "classogl_1_1FrameBuffer.html", null ],
      [ "ogl::RenderBuffer", "classogl_1_1RenderBuffer.html", null ],
      [ "ogl::UniformBuffer", "classogl_1_1UniformBuffer.html", null ],
      [ "ogl::VertexArray", "classogl_1_1VertexArray.html", null ],
      [ "ogl::VertexBuffer", "classogl_1_1VertexBuffer.html", null ]
    ] ],
    [ "ogl::Camera", "classogl_1_1Camera.html", null ],
    [ "ogl::CameraInfo", "structogl_1_1CameraInfo.html", null ],
    [ "ogl::CameraRotation", "structogl_1_1CameraRotation.html", null ],
    [ "ogl::CameraVectors", "structogl_1_1CameraVectors.html", null ],
    [ "CollisionPoints", "structCollisionPoints.html", null ],
    [ "Color", "structColor.html", null ],
    [ "Component", "classComponent.html", [
      [ "BehaviourComponent", "classBehaviourComponent.html", null ],
      [ "BufferComponent", "classBufferComponent.html", null ],
      [ "CameraComponent", "classCameraComponent.html", null ],
      [ "ColliderComponent", "classColliderComponent.html", null ],
      [ "HideTreeComponent", "classHideTreeComponent.html", null ],
      [ "ImportedMeshTextures", "classImportedMeshTextures.html", null ],
      [ "InputComponent", "classInputComponent.html", null ],
      [ "InstancedComponent", "classInstancedComponent.html", null ],
      [ "LightComponent", "classLightComponent.html", null ],
      [ "MaterialComponent", "classMaterialComponent.html", null ],
      [ "MultiMesh", "classMultiMesh.html", null ],
      [ "Outlined", "classOutlined.html", null ],
      [ "ParentComponent", "classParentComponent.html", null ],
      [ "PhysicComponent", "classPhysicComponent.html", null ],
      [ "RenderComponent", "classRenderComponent.html", null ],
      [ "ShaderComponent", "classShaderComponent.html", null ],
      [ "SkyboxComponent", "classSkyboxComponent.html", null ],
      [ "TextureComponent", "classTextureComponent.html", null ],
      [ "TimeAnimation", "classTimeAnimation.html", null ],
      [ "Transform", "classTransform.html", null ],
      [ "VertexComponent", "classVertexComponent.html", null ]
    ] ],
    [ "EntityManager", "classEntityManager.html", null ],
    [ "ogl::Event", "classogl_1_1Event.html", null ],
    [ "ogl::EventManager", "classogl_1_1EventManager.html", null ],
    [ "FBConfig", "structFBConfig.html", null ],
    [ "ogl::ImGuiPanel", "classogl_1_1ImGuiPanel.html", [
      [ "ImGuiEntityTree", "classImGuiEntityTree.html", null ],
      [ "ImGuiNormalView", "classImGuiNormalView.html", null ]
    ] ],
    [ "ImportedTexture", "structImportedTexture.html", null ],
    [ "ogl::InputManager", "classogl_1_1InputManager.html", null ],
    [ "InstanceData", "structInstanceData.html", null ],
    [ "Key", "structKey.html", null ],
    [ "ogl::Layer", "classogl_1_1Layer.html", [
      [ "CustomLayer", "classCustomLayer.html", null ],
      [ "PhysicWorld", "classPhysicWorld.html", null ],
      [ "ogl::ImGuiManager", "classogl_1_1ImGuiManager.html", null ],
      [ "ogl::TextManager", "classogl_1_1TextManager.html", null ],
      [ "ogl::Window", "classogl_1_1Window.html", null ]
    ] ],
    [ "LightConstraint", "structLightConstraint.html", null ],
    [ "LightShaderBlock", "structLightShaderBlock.html", null ],
    [ "LightVectors", "structLightVectors.html", null ],
    [ "Material", "classMaterial.html", null ],
    [ "MeshInfo", "structMeshInfo.html", null ],
    [ "Pair< T >", "structPair.html", null ],
    [ "ogl::Primitive", "structogl_1_1Primitive.html", null ],
    [ "Profiler", "classProfiler.html", [
      [ "LinuxProfiler", "classLinuxProfiler.html", null ]
    ] ],
    [ "RBConfig", "structRBConfig.html", null ],
    [ "ogl::Renderer", "classogl_1_1Renderer.html", null ],
    [ "ogl::RendererStats", "structogl_1_1RendererStats.html", null ],
    [ "ogl::Resource", "classogl_1_1Resource.html", null ],
    [ "ogl::ResourceManager", "classogl_1_1ResourceManager.html", null ],
    [ "ogl::Shader", "classogl_1_1Shader.html", null ],
    [ "ogl::ShaderProgram", "classogl_1_1ShaderProgram.html", null ],
    [ "Solver", "classSolver.html", [
      [ "CollisionSolver", "classCollisionSolver.html", null ],
      [ "ForceSolver", "classForceSolver.html", null ],
      [ "GravitySolver", "classGravitySolver.html", null ],
      [ "PositionSolver", "classPositionSolver.html", null ],
      [ "VelocitySolver", "classVelocitySolver.html", null ]
    ] ],
    [ "State", "classState.html", [
      [ "BootstrapState", "classBootstrapState.html", null ],
      [ "NormalViewState", "classNormalViewState.html", null ]
    ] ],
    [ "StateManager", "classStateManager.html", null ],
    [ "stbi_io_callbacks", "structstbi__io__callbacks.html", null ],
    [ "ogl::Text", "classogl_1_1Text.html", null ],
    [ "ogl::TextHelper", "structogl_1_1TextHelper.html", null ],
    [ "ogl::TextSettings", "structogl_1_1TextSettings.html", null ],
    [ "ogl::Texture", "classogl_1_1Texture.html", null ],
    [ "TextureParams", "structTextureParams.html", null ],
    [ "ogl::WindowCallbacks", "structogl_1_1WindowCallbacks.html", null ],
    [ "ogl::WindowSettings", "structogl_1_1WindowSettings.html", null ]
];